on: [push, pull_request]
name: Continuous Integration

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      # FIXME: Setup will fail if you use a Python version lower than 3.9
      - name: Force Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      # We'd love to use the action but the action isn't exactly clean so we're going to do this the manual way.
      - name: Setup Bazel
        run: |
          sudo apt-get -y install apt-transport-https curl gnupg && \
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg && \
          sudo mv bazel.gpg /etc/apt/trusted.gpg.d/ && \
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list;

          sudo apt-get update && sudo apt-get install bazel -y
      
      - name: Build (Native)
        run: |
         pip install numpy
         python build.py build --desktop cpu --include_opencv_libs -v
      
      - name: Build (.NET)
        run: dotnet build -c Debug ./src/Akihabara.sln
      
      - name: Test
        run: dotnet test $pwd/src/*.Tests/bin/Debug/*/*.Tests.dll --logger "trx;LogFileName=TestResults-Linux.trx"
        shell: pwsh

      # Attempt to upload results even if test fails.
      # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#always
      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: TestResults-Linux
          path: ${{github.workspace}}/TestResults/TestResults-Linux.trx
